language: python
python: 3.6

env:
  - DJANGO_VERSION=3.1.1
  - DJANGO_SETTINGS_MODULE='task_manager.settings'

install: make

before_install:
  - pip install poetry

script:
  - make lint
  - make test

after_success:
  - coveralls
