# Generated by Django 3.1.1 on 2020-09-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_status_name', models.CharField(choices=[('NEW', 'new'), ('WORK', 'in work'), ('TEST', 'in testing'), ('DONE', 'finished')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=5000)),
                ('status', models.CharField(choices=[('NEW', 'new'), ('WORK', 'in work'), ('TEST', 'in testing'), ('DONE', 'finished')], default='NEW', max_length=4)),
                ('creator', models.CharField(max_length=200)),
                ('assigned_to', models.CharField(max_length=200)),
                ('tags', models.ManyToManyField(to='tasks.Tag')),
            ],
        ),
    ]
