# Generated by Django 3.1.1 on 2020-09-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
