# Generated by Django 3.1.1 on 2020-09-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskstatus',
            name='task_status_name',
        ),
        migrations.AddField(
            model_name='taskstatus',
            name='status_name',
            field=models.CharField(choices=[('NEW', 'new'), ('WORK', 'in work'), ('TEST', 'in testing'), ('DONE', 'finished')], default='NEW', max_length=4),
        ),
    ]
