# Generated by Django 3.1.1 on 2020-09-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20200915_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('WORK', 'In work'), ('TEST', 'Testing'), ('DONE', 'Done')], default='NEW', max_length=4),
        ),
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='tasks.Tag'),
        ),
        migrations.AlterField(
            model_name='taskstatus',
            name='status_name',
            field=models.CharField(choices=[('NEW', 'New'), ('WORK', 'In work'), ('TEST', 'Testing'), ('DONE', 'Done')], default='NEW', max_length=4),
        ),
    ]
